histogram aggregation test improved.
handcraftedinthealps/ElasticsearchDSL pull request #23
Opened 2022-08-26 11:48 UTC by hkulekci

- Histogram aggregation tests improved. 
 - Aggregation test broken namespaces fixed. 
 - HistogramAggregation extended_bounds deprecation error fixed for `strlen` function

2022-08-27 11:20 UTC, hkulekci commented
@alexander-schranz Ping

2023-01-27 00:04 UTC, hkulekci commented
Hello @alexander-schranz, could you check this PR?

2023-01-27 00:08 UTC, alexander-schranz requested changes
Sorry for the late response.

2023-01-27 00:08 UTC, alexander-schranz commented on src/Aggregation/Bucketing/HistogramAggregation.php
> +            }
Looks like this should also be fixed for 7.x version. Or does it only appear on 8.x?

2023-01-27 00:13 UTC, hkulekci commented on src/Aggregation/Bucketing/HistogramAggregation.php
> +            }
I could not remember exactly, but I think it should be.

2023-01-27 00:14 UTC, alexander-schranz commented on src/Aggregation/Bucketing/HistogramAggregation.php
> +            }
Can you then rebase the PR to 7.x then?

2023-01-27 00:30 UTC, alexander-schranz commented
fixed in #24 and merged back to 8.x.

@hkulekci Thank you!

2023-01-27 00:30 UTC, closed without merging

2023-01-27 00:33 UTC, alexander-schranz commented
Tagged as 8.0.1